In [1]:
import os
os.getcwd()

'C:\\Users\\MAHENDRA'

In [2]:
os.chdir("C:/Users/MAHENDRA/Desktop/DATA SET1")
os.getcwd()

'C:\\Users\\MAHENDRA\\Desktop\\DATA SET1'

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
get_ipython().magic('matplotlib inline')

In [4]:
df=pd.read_csv('t3-fertilizer4.csv')

In [5]:
df

Temparature  Humidity   Moisture Soil Type    Crop Type  Nitrogen  \
0            26         52        38     Sandy        Maize        37   
1            29         52        45     Loamy    Sugarcane        12   
2            34         65        62     Black       Cotton         7   
3            32         62        34       Red      Tobacco        22   
4            28         54        46    Clayey        Paddy        35   
5            26         52        35     Sandy       Barley        12   
6            25         50        64       Red       Cotton         9   
7            33         64        50     Loamy        Wheat        41   
8            30         60        42     Sandy      Millets        21   
9            29         58        33     Black    Oil seeds         9   
10           27         54        28    Clayey       Pulses        13   
11           31         62        48     Sandy        Maize        14   
12           25         50        65     Loamy       Cotton        36   
13           32         62        41    Clayey        Paddy        24   
14           26         52        31       Red  Ground Nuts        14   
15           31         62        49     Black    Sugarcane        10   
16           33         64        34    Clayey       Pulses        38   
17           25         50        39     Sandy       Barley        21   
18           28         54        65     Black       Cotton        39   
19           29         58        52     Loamy        Wheat        13   
20           30         60        44     Sandy      Millets        10   
21           34         65        53     Loamy    Sugarcane        12   
22           35         68        33       Red      Tobacco        11   
23           28         54        37     Black      Millets        36   
24           33         64        39    Clayey        Paddy        13   
25           26         52        44     Sandy        Maize        23   
26           30         60        63       Red       Cotton         9   
27           32         62        30     Loamy    Sugarcane        38   
28           37         70        32     Black    Oil seeds        12   
29           26         52        36    Clayey       Pulses        14   
..          ...        ...       ...       ...          ...       ...   
69           30         60        38     Sandy      Millets        10   
70           26         52        39    Clayey       Pulses        21   
71           31         62        32       Red      Tobacco        39   
72           34         65        48     Loamy        Wheat        23   
73           27         53        34     Black    Oil seeds        42   
74           33         64        31       Red  Ground Nuts        13   
75           29         58        42    Clayey        Paddy         9   
76           30         60        47     Sandy        Maize        22   
77           27         53        59     Loamy    Sugarcane        10   
78           26         52        36    Clayey       Pulses         7   
79           34         65        63       Red       Cotton        14   
80           28         54        43    Clayey        Paddy        10   
81           30         60        40     Sandy      Millets        41   
82           29         58        65     Black       Cotton        14   
83           26         52        59     Loamy    Sugarcane        11   
84           31         62        44     Sandy       Barley        21   
85           35         67        28    Clayey       Pulses         8   
86           29         58        30       Red      Tobacco        13   
87           27         53        30     Black      Millets        35   
88           36         68        50     Loamy        Wheat        12   
89           29         58        61     Loamy       Cotton        11   
90           30         60        26     Black    Oil seeds         8   
91           34         65        45    Clayey        Paddy   

In [6]:
df.describe()

Temparature  Humidity    Moisture   Nitrogen  Potassium  Phosphorous
count    99.000000  99.000000  99.000000  99.000000  99.000000    99.000000
mean     30.282828  59.151515  43.181818  18.909091   3.383838    18.606061
std       3.502304   5.840331  11.271568  11.599693   5.814667    13.476978
min      25.000000  50.000000  25.000000   4.000000   0.000000     0.000000
25%      28.000000  54.000000  34.000000  10.000000   0.000000     9.000000
50%      30.000000  60.000000  41.000000  13.000000   0.000000    19.000000
75%      33.000000  64.000000  50.500000  24.000000   7.500000    30.000000
max      38.000000  72.000000  65.000000  42.000000  19.000000    42.000000

In [7]:
df.cov()

Temparature  Humidity     Moisture    Nitrogen  Potassium  \
Temparature    12.266131  19.905690    3.601113   -1.371985  -0.477015   
Humidity       19.905690  34.109462    6.012987   -4.108534  -0.130179   
Moisture        3.601113   6.012987  127.048237  -12.544527   1.817254   
Nitrogen       -1.371985  -4.108534  -12.544527  134.552876 -33.730056   
Potassium      -0.477015  -0.130179    1.817254  -33.730056  33.810348   
Phosphorous     9.796228  16.060297    1.409091 -107.393321   6.989487   

             Phosphorous  
Temparature     9.796228  
Humidity       16.060297  
Moisture        1.409091  
Nitrogen     -107.393321  
Potassium       6.989487  
Phosphorous   181.628942

In [8]:
df.columns

Index(['Temparature', 'Humidity ', 'Moisture', 'Soil Type', 'Crop Type',
       'Nitrogen', 'Potassium', 'Phosphorous', 'Fertilizer Name'],
      dtype='object')

In [9]:
df.dtypes

Temparature         int64
Humidity            int64
Moisture            int64
Soil Type          object
Crop Type          object
Nitrogen            int64
Potassium           int64
Phosphorous         int64
Fertilizer Name    object
dtype: object

In [10]:
df.head()

Temparature  Humidity   Moisture Soil Type  Crop Type  Nitrogen  Potassium  \
0           26         52        38     Sandy      Maize        37          0   
1           29         52        45     Loamy  Sugarcane        12          0   
2           34         65        62     Black     Cotton         7          9   
3           32         62        34       Red    Tobacco        22          0   
4           28         54        46    Clayey      Paddy        35          0   

   Phosphorous Fertilizer Name  
0            0            Urea  
1           36             DAP  
2           30        14-35-14  
3           20           28-28  
4            0            Urea

In [11]:
df.tail()

Temparature  Humidity   Moisture Soil Type  Crop Type  Nitrogen  \
94           25         50        32    Clayey     Pulses        24   
95           30         60        27       Red    Tobacco         4   
96           38         72        51     Loamy      Wheat        39   
97           36         60        43     Sandy    Millets        15   
98           29         58        57     Black  Sugarcane        12   

    Potassium  Phosphorous Fertilizer Name  
94          0           19           28-28  
95         17           17        10-26-26  
96          0            0            Urea  
97          0           41             DAP  
98          0           10           20-20

In [12]:
df.corr()

Temparature  Humidity   Moisture  Nitrogen  Potassium  \
Temparature     1.000000   0.973164  0.091222 -0.033771  -0.023424   
Humidity        0.973164   1.000000  0.091342 -0.060646  -0.003833   
Moisture        0.091222   0.091342  1.000000 -0.095945   0.027727   
Nitrogen       -0.033771  -0.060646 -0.095945  1.000000  -0.500087   
Potassium      -0.023424  -0.003833  0.027727 -0.500087   1.000000   
Phosphorous     0.207545   0.204044  0.009276 -0.686971   0.089192   

             Phosphorous  
Temparature     0.207545  
Humidity        0.204044  
Moisture        0.009276  
Nitrogen       -0.686971  
Potassium       0.089192  
Phosphorous     1.000000

In [13]:
x=df.iloc[:,0:8].values


In [14]:
x

array([[26, 52, 38, 'Sandy', 'Maize', 37, 0, 0],
       [29, 52, 45, 'Loamy', 'Sugarcane', 12, 0, 36],
       [34, 65, 62, 'Black', 'Cotton', 7, 9, 30],
       [32, 62, 34, 'Red', 'Tobacco', 22, 0, 20],
       [28, 54, 46, 'Clayey', 'Paddy', 35, 0, 0],
       [26, 52, 35, 'Sandy', 'Barley', 12, 10, 13],
       [25, 50, 64, 'Red', 'Cotton', 9, 0, 10],
       [33, 64, 50, 'Loamy', 'Wheat', 41, 0, 0],
       [30, 60, 42, 'Sandy', 'Millets', 21, 0, 18],
       [29, 58, 33, 'Black', 'Oil seeds', 9, 7, 30],
       [27, 54, 28, 'Clayey', 'Pulses', 13, 0, 40],
       [31, 62, 48, 'Sandy', 'Maize', 14, 15, 12],
       [25, 50, 65, 'Loamy', 'Cotton', 36, 0, 0],
       [32, 62, 41, 'Clayey', 'Paddy', 24, 0, 22],
       [26, 52, 31, 'Red', 'Ground Nuts', 14, 0, 41],
       [31, 62, 49, 'Black', 'Sugarcane', 10, 13, 14],
       [33, 64, 34, 'Clayey', 'Pulses', 38, 0, 0],
       [25, 50, 39, 'Sandy', 'Barley', 21, 0, 19],
       [28, 54, 65, 'Black', 'Cotton', 39, 0, 0],
       [29, 58, 52, 'Loamy',

In [15]:
y=df.iloc[:,8].values

In [16]:
y

array(['Urea', 'DAP', '14-35-14', '28-28', 'Urea', '17-17-17', '20-20',
       'Urea', '28-28', '14-35-14', 'DAP', '17-17-17', 'Urea', '28-28',
       'DAP', '17-17-17', 'Urea', '28-28', 'Urea', 'DAP', '20-20',
       '17-17-17', 'DAP', 'Urea', '20-20', '28-28', '14-35-14', 'Urea',
       'DAP', '20-20', '28-28', 'DAP', 'Urea', '14-35-14', '28-28',
       'Urea', '14-35-14', 'DAP', '17-17-17', 'DAP', '20-20', '14-35-14',
       '28-28', 'Urea', 'DAP', '14-35-14', '20-20', '28-28', 'Urea',
       '14-35-14', '28-28', '20-20', 'Urea', 'DAP', '17-17-17', '28-28',
       'Urea', '20-20', '17-17-17', 'DAP', 'Urea', '20-20', '28-28',
       '10-26-26', 'Urea', 'DAP', '20-20', '14-35-14', '10-26-26',
       '20-20', '28-28', 'Urea', '28-28', 'Urea', 'DAP', '14-35-14',
       '28-28', '20-20', '10-26-26', 'DAP', '14-35-14', 'Urea', 'DAP',
       '20-20', '28-28', '14-35-14', '10-26-26', 'Urea', '10-26-26',
       'DAP', '14-35-14', '10-26-26', 'Urea', '14-35-14', '28-28',
       '10-26-26', 'U

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
lb=LabelEncoder()
x[:,4]=lb.fit_transform(x[:,4])
x[:,3]=lb.fit_transform(x[:,3])

In [19]:
x

array([[26, 52, 38, 4, 3, 37, 0, 0],
       [29, 52, 45, 2, 8, 12, 0, 36],
       [34, 65, 62, 0, 1, 7, 9, 30],
       [32, 62, 34, 3, 9, 22, 0, 20],
       [28, 54, 46, 1, 6, 35, 0, 0],
       [26, 52, 35, 4, 0, 12, 10, 13],
       [25, 50, 64, 3, 1, 9, 0, 10],
       [33, 64, 50, 2, 10, 41, 0, 0],
       [30, 60, 42, 4, 4, 21, 0, 18],
       [29, 58, 33, 0, 5, 9, 7, 30],
       [27, 54, 28, 1, 7, 13, 0, 40],
       [31, 62, 48, 4, 3, 14, 15, 12],
       [25, 50, 65, 2, 1, 36, 0, 0],
       [32, 62, 41, 1, 6, 24, 0, 22],
       [26, 52, 31, 3, 2, 14, 0, 41],
       [31, 62, 49, 0, 8, 10, 13, 14],
       [33, 64, 34, 1, 7, 38, 0, 0],
       [25, 50, 39, 4, 0, 21, 0, 19],
       [28, 54, 65, 0, 1, 39, 0, 0],
       [29, 58, 52, 2, 10, 13, 0, 36],
       [30, 60, 44, 4, 4, 10, 0, 9],
       [34, 65, 53, 2, 8, 12, 14, 12],
       [35, 68, 33, 3, 9, 11, 0, 37],
       [28, 54, 37, 0, 4, 36, 0, 0],
       [33, 64, 39, 1, 6, 13, 0, 10],
       [26, 52, 44, 4, 3, 23, 0, 20],
       [30, 60, 6

In [20]:
x.shape

(99, 8)

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
lb2=LabelEncoder()
y=lb2.fit_transform(y)

In [23]:
y

array([6, 5, 1, 4, 6, 2, 3, 6, 4, 1, 5, 2, 6, 4, 5, 2, 6, 4, 6, 5, 3, 2,
       5, 6, 3, 4, 1, 6, 5, 3, 4, 5, 6, 1, 4, 6, 1, 5, 2, 5, 3, 1, 4, 6,
       5, 1, 3, 4, 6, 1, 4, 3, 6, 5, 2, 4, 6, 3, 2, 5, 6, 3, 4, 0, 6, 5,
       3, 1, 0, 3, 4, 6, 4, 6, 5, 1, 4, 3, 0, 5, 1, 6, 5, 3, 4, 1, 0, 6,
       0, 5, 1, 0, 6, 1, 4, 0, 6, 5, 3])

In [24]:
from sklearn.preprocessing import OneHotEncoder

In [25]:
onehotencoder = OneHotEncoder(categorical_features = [3])
x = onehotencoder.fit_transform(x).toarray()
x = x[:, 1:]

C:\Users\MAHENDRA\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\MAHENDRA\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [26]:
x

array([[ 0.,  0.,  0., ..., 37.,  0.,  0.],
       [ 0.,  1.,  0., ..., 12.,  0., 36.],
       [ 0.,  0.,  0., ...,  7.,  9., 30.],
       ...,
       [ 0.,  1.,  0., ..., 39.,  0.,  0.],
       [ 0.,  0.,  0., ..., 15.,  0., 41.],
       [ 0.,  0.,  0., ..., 12.,  0., 10.]])

In [27]:
x.shape

(99, 11)

In [28]:
y=y.reshape(-1,1)
y.ndim

2

In [29]:
import statsmodels.api as sm
model1=sm.OLS(y,x).fit()
predictions=model1.predict()
model1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.973
Model:                            OLS   Adj. R-squared:                  0.970
Method:                 Least Squares   F-statistic:                     288.2
Date:                Fri, 21 Jun 2019   Prob (F-statistic):           5.39e-64
Time:                        12:29:12   Log-Likelihood:                -101.92
No. Observations:                  99   AIC:                             225.8
Df Residuals:                      88   BIC:                             254.4
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0115      0.240      0.048      0.962      -0.466       0.489
x2             0.1352      0.274      0.493      0.624      -0.410       0.681
x3             0.1699      0.245      0.694      0.489      -0.317       0.656
x4             0.1177      0.245      0.481      0.632      -0.369       0.604
x5             0.0132      0.083      0.160      0.874      -0.151       0.178
x6             0.0109      0.045      0.242      0.809      -0.078       0.100
x7             0.0051      0.008      0.679      0.499      -0.010       0.020
x8            -0.0204      0.034     -0.595      0.554      -0.088       0.048
x9             0.1207      0.011     11.414      0.000       0.100       0.142
x10           -0.1626      0.016    -10.425      0.000      -0.194      -0.132
x11            0.0346      0.009      3.973      0.000       0.017       0.052
==============================================================================
Omnibus:                       15.608   Durbin-Watson:                   1.838
Prob(Omnibus):                  0.000   Jarque-Bera (JB):                4.514
Skew:                          -0.100   Prob(JB):                        0.105
Kurtosis:                       1.973   Cond. No.                         443.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [30]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [31]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [32]:
from sklearn.tree import DecisionTreeClassifier

In [33]:
dt=DecisionTreeClassifier()

In [34]:
dt.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [35]:
y_pred=dt.predict(x_test)

In [36]:
from sklearn.metrics import accuracy_score

In [37]:
accuracy_score(y_test,y_pred)

0.9